SELECT
	TEAM,
	ROUND(100 / SUM(ATTEMPTED_FIELD_GOALS)::DECIMAL, 3)* SUM(MADE_FIELD_GOALS) TIRO_NORMAL,
	ROUND(100 / SUM(ATTEMPTED_FREE_THROWS)::DECIMAL, 3)* SUM(MADE_FREE_THROWS) TIRO_LIBRE,
	ROUND(100 / SUM(ATTEMPTED_THREE_POINT_FIELD_GOALS)::DECIMAL, 3)* SUM(MADE_THREE_POINT_FIELD_GOALS::DECIMAL) TIRO_DE_TRES
FROM
	TEAM_BOX_SCORE
GROUP BY
	TEAM
ORDER BY
	TIRO_NORMAL DESC,
	TIRO_LIBRE DESC,
	TIRO_DE_TRES DESC