SELECT
	TEAM, ROUND(100/(WIN+LOSS)::DECIMAL * WIN,3)::DECIMAL efficiency
FROM
	(SELECT
		TEAM,
		SUM(CASE
			WHEN OUTCOME = 'WIN'
			THEN 1
			ELSE 0
		END) WIN,
		SUM(CASE
		   WHEN OUTCOME = 'LOSS'
		   THEN 1
		   ELSE 0
		END) LOSS
	FROM
		TEAM_BOX_SCORE
	GROUP BY
		TEAM) RESULT
ORDER BY
	efficiency desc