SELECT
	TEAM,
	ROUND((100 / SUM(ATTEMPTED_FIELD_GOALS)::DECIMAL)* SUM(MADE_FIELD_GOALS)/100, 3)::TEXT PERCENTAGE_MADE_FIELD_GOALS,
	ROUND((100 / SUM(ATTEMPTED_FREE_THROWS)::DECIMAL)* SUM(MADE_FREE_THROWS)/100, 3)::TEXT PERCENTAGE_MADE_FREE_THROWS,
	ROUND((100 / SUM(ATTEMPTED_THREE_POINT_FIELD_GOALS)::DECIMAL)* SUM(MADE_THREE_POINT_FIELD_GOALS::DECIMAL)/100, 3)::TEXT PERCENTAGE_MADE_THREE_POINT_FIELD_GOALS
FROM
	TEAM_BOX_SCORE
GROUP BY
	TEAM
ORDER BY
	PERCENTAGE_MADE_FIELD_GOALS DESC,
	PERCENTAGE_MADE_FREE_THROWS DESC,
	PERCENTAGE_MADE_THREE_POINT_FIELD_GOALS DESC