SELECT
	PBS.DATE AS DATE,
	PBS.TEAM HOME_TEAM,
	--EF.EFFICIENCY,
	PBS.OPPONENT AWAY_TEAM,
	--EF_AWAY.EFFICIENCY,
	ROUND(CASE
		-- Inicio Primera condicional
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) > 0.045
		AND
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.055
		AND
			EF.EFFICIENCY > EF_AWAY.EFFICIENCY
		THEN 0.5 + ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY)
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) > 0.045
		AND
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.055
		AND
			EF.EFFICIENCY < EF_AWAY.EFFICIENCY
		THEN 1 - (0.5 + ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY))
		-- Fin Primera condicional

		-- Inicio Segunda condicional
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) > 0.3
        AND
			EF.EFFICIENCY > EF_AWAY.EFFICIENCY
		THEN 0.5 + (ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY)/2)
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) > 0.3
        AND
			EF.EFFICIENCY < EF_AWAY.EFFICIENCY
		THEN 1 - (0.5 + (ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY)/2))
		-- Fin Segunda condicional

        -- Inicio Tercera condicional
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.15
        AND
			EF.EFFICIENCY > EF_AWAY.EFFICIENCY
		THEN (0.45 + ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY))
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.15
        AND
			EF.EFFICIENCY < EF_AWAY.EFFICIENCY
		THEN 1 - (0.45 + ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY))
		-- Fin Tercera condicional

        -- Inicio Cuarta condicional
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.3
        AND
			EF.EFFICIENCY > EF_AWAY.EFFICIENCY
		THEN 1 - (0.15 + (ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY)/2))
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.3
        AND
			EF.EFFICIENCY < EF_AWAY.EFFICIENCY
		THEN 0.15 + (ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY)/2)
		-- Fin Cuarta condicional

		ELSE 0.5 + (EF.EFFICIENCY * EF_AWAY.EFFICIENCY)/4
	END,4)::TEXT PREDICTION_HOME_TEAM,
	ROUND(CASE
		-- Inicio Primera condicional
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) > 0.045
		AND
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.055
		AND
			EF.EFFICIENCY < EF_AWAY.EFFICIENCY
		THEN 0.5 + ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY)
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) > 0.045
		AND
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.055
		AND
			EF.EFFICIENCY > EF_AWAY.EFFICIENCY
		THEN 1 - (0.5 + ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY))
		-- Fin Primera condicional

        -- Inicio Segunda condicional
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) > 0.3
        AND
			EF.EFFICIENCY < EF_AWAY.EFFICIENCY
		THEN 0.5 + (ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY)/2)
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) > 0.3
        AND
			EF.EFFICIENCY > EF_AWAY.EFFICIENCY
		THEN 1 - (0.5 + (ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY)/2))
		-- Fin Segunda condicional

        -- Inicio Tercera condicional
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.15
        AND
			EF.EFFICIENCY < EF_AWAY.EFFICIENCY
		THEN (0.45 + ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY))
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.15
        AND
			EF.EFFICIENCY > EF_AWAY.EFFICIENCY
		THEN 1 - (0.45 + ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY))
		-- Fin Tercera condicional

        -- Inicio Cuarta condicional
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.3
        AND
			EF.EFFICIENCY < EF_AWAY.EFFICIENCY
		THEN 1 - (0.15 + (ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY)/2))
		WHEN
			ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY) < 0.3
        AND
			EF.EFFICIENCY > EF_AWAY.EFFICIENCY
		THEN 0.15 + (ABS(EF.EFFICIENCY - EF_AWAY.EFFICIENCY)/2)
		-- Fin Cuarta condicional

		ELSE 1 - (0.5 + (EF.EFFICIENCY * EF_AWAY.EFFICIENCY)/4)
	END,4)::TEXT PREDICTION_AWAY_TEAM
FROM
	(SELECT DISTINCT
		PBS.DATE,
		PBS.TEAM,
		PBS.OPPONENT,
		PBS.LOCATION
	FROM
		PLAYER_BOX_SCORE PBS
	WHERE
		PBS.LOCATION = 'HOME') PBS,
	(SELECT
		TEAM, ROUND((100/(WIN+LOSS)::DECIMAL * WIN)/100,15)::DECIMAL efficiency
	FROM
		(SELECT
			TEAM,
			SUM(
			CASE
				WHEN OUTCOME = 'WIN'
				THEN 1
				ELSE 0
			END) WIN,
			SUM(CASE
		   		WHEN OUTCOME = 'LOSS'
		   		THEN 1
		   		ELSE 0
			END) LOSS
		FROM
			TEAM_BOX_SCORE
		GROUP BY
			TEAM) RESULT
		ORDER BY
			efficiency desc) EF,
	(SELECT
		TEAM, ROUND((100/(WIN+LOSS)::DECIMAL * WIN)/100,15)::DECIMAL efficiency
	FROM
		(SELECT
			TEAM,
			SUM(
			CASE
				WHEN OUTCOME = 'WIN'
				THEN 1
				ELSE 0
			END) WIN,
			SUM(CASE
		   		WHEN OUTCOME = 'LOSS'
		   		THEN 1
		   		ELSE 0
			END) LOSS
		FROM
			TEAM_BOX_SCORE
		GROUP BY
			TEAM) RESULT
		ORDER BY
			efficiency desc) EF_AWAY
WHERE
	PBS.TEAM = EF.TEAM
AND
	PBS.OPPONENT = EF_AWAY.TEAM
ORDER BY
    DATE ASC