SELECT
	PBS.TEAM,
	SUM(PBS.ASSISTS) ASSISTS,
	SUM(PBS_OPPONENT.ASSISTS) ASSISTS_OPPONENT,
	ROUND((100 / (SUM(PBS.ASSISTS) + SUM(PBS_OPPONENT.ASSISTS))::DECIMAL) * (SUM(PBS.ASSISTS)), 2) ASSISTS_PERCENTAGE,
	SUM(PBS.BLOCKS) BLOCKS,
	SUM(PBS_OPPONENT.BLOCKS) BLOCKS_OPPONENT,
	ROUND((100 / (SUM(PBS.BLOCKS) + SUM(PBS_OPPONENT.BLOCKS))::DECIMAL) * (SUM(PBS.BLOCKS)), 2) BLOCKS_PERCENTAGE,
	SUM(PBS.DEFENSIVE_REBOUNDS) DEFENSIVE_REBOUNDS,
	SUM(PBS_OPPONENT.DEFENSIVE_REBOUNDS) DEFENSIVE_REBOUNDS_OPPONENT,
	ROUND((100 / (SUM(PBS.DEFENSIVE_REBOUNDS) + SUM(PBS_OPPONENT.DEFENSIVE_REBOUNDS))::DECIMAL) * (SUM(PBS.DEFENSIVE_REBOUNDS)), 2) DEFENSIVE_REBOUNDS_PERCENTAGE,
	SUM(PBS.OFFENSIVE_REBOUNDS) OFFENSIVE_REBOUNDS,
	SUM(PBS_OPPONENT.OFFENSIVE_REBOUNDS) OFFENSIVE_REBOUNDS_OPPONENT,
	ROUND((100 / (SUM(PBS.OFFENSIVE_REBOUNDS) + SUM(PBS_OPPONENT.OFFENSIVE_REBOUNDS))::DECIMAL) * (SUM(PBS.OFFENSIVE_REBOUNDS)), 2) OFFENSIVE_REBOUNDS_PERCENTAGE,
	SUM(PBS.STEALS) STEALS,
	SUM(PBS_OPPONENT.STEALS) STEALS_OPPONENT,
	ROUND((100 / (SUM(PBS.STEALS) + SUM(PBS_OPPONENT.STEALS))::DECIMAL) * (SUM(PBS.STEALS)), 2) STEALS_PERCENTAGE,
	SUM(PBS.TURNOVERS) TURNOVERS,
	SUM(PBS_OPPONENT.TURNOVERS) TURNOVERS_OPPONENT,
	ROUND((100 / (SUM(PBS.TURNOVERS) + SUM(PBS_OPPONENT.TURNOVERS))::DECIMAL) * (SUM(PBS.TURNOVERS)), 2) TURNOVERS_PERCENTAGE
FROM
	(SELECT 
		PBS.TEAM,
		PBS.DATE,
		SUM(PBS.ASSISTS) ASSISTS,
		SUM(PBS.BLOCKS) BLOCKS,
		SUM(PBS.DEFENSIVE_REBOUNDS) DEFENSIVE_REBOUNDS,
		SUM(PBS.OFFENSIVE_REBOUNDS) OFFENSIVE_REBOUNDS,
		SUM(PBS.STEALS) STEALS,
		SUM(PBS.TURNOVERS) TURNOVERS,
		PBS.OPPONENT
	FROM 
		PLAYER_BOX_SCORE PBS
	GROUP BY
		PBS.TEAM,
		PBS.DATE,
		PBS.OPPONENT,
		PBS.LOCATION) PBS,
	(SELECT 
		PBS.TEAM,
		PBS.DATE,
		SUM(PBS.ASSISTS) ASSISTS,
		SUM(PBS.BLOCKS) BLOCKS,
		SUM(PBS.DEFENSIVE_REBOUNDS) DEFENSIVE_REBOUNDS,
		SUM(PBS.OFFENSIVE_REBOUNDS) OFFENSIVE_REBOUNDS,
		SUM(PBS.STEALS) STEALS,
		SUM(PBS.TURNOVERS) TURNOVERS,
		PBS.OPPONENT
	FROM 
		PLAYER_BOX_SCORE PBS
	GROUP BY
		PBS.TEAM,
		PBS.DATE,
		PBS.OPPONENT,
		PBS.LOCATION) PBS_OPPONENT
WHERE
	PBS_OPPONENT.TEAM = PBS.OPPONENT
AND
	PBS.TEAM = PBS_OPPONENT.OPPONENT
AND
	PBS.DATE = PBS_OPPONENT.DATE
GROUP BY
	PBS.TEAM