SELECT
	TEAM,
	COUNT(DATE) GAMES_PLAYED,
	ROUND(SUM(OFFENSIVE_REBOUNDS) / COUNT(DATE)::DECIMAL,3)::TEXT MADE_OFFENSIVE_REBOUNDS,
	ROUND(SUM(DEFENSIVE_REBOUNDS) / COUNT(DATE)::DECIMAL,3)::TEXT MADE_DEFENSIVE_REBOUNDS,
	ROUND(SUM(BLOCKS::DECIMAL) / COUNT(DATE)::DECIMAL,3)::TEXT MADE_BLOCKS,
	ROUND(SUM(TURNOVERS) / COUNT(DATE)::DECIMAL,3)::TEXT MADE_TURNOVERS,
	ROUND(SUM(POINTS) / COUNT(DATE)::DECIMAL,3)::TEXT MADE_POINTS
FROM
	team_box_score
GROUP BY
	TEAM